# build stage
FROM golang:1.25-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-s -w" -o /out/chat-client ./cmd/client

# runtime stage
FROM alpine:3.22.2
RUN apk add --no-cache ca-certificates bash
COPY --from=builder /out/chat-client /usr/local/bin/chat-client
ENTRYPOINT ["/usr/local/bin/chat-client"]